### ISSUE TITLE
What does the term "license possible" mean?

### ISSUE THREAD

**Issue by krysnuvadga** [krysnuvadga/license-coverage-grader#6]
@kestewart From the rough pseudo code I was give by Kate, I have to get the "total number of license possible" I don't understand the term "license possible".

```
main() {
 num_total_files = 0
 num_source_files = 0
 num_license_concluded = 0 
 num_license_possible = 0


 print package name

for every file in package {
    ++num_total_files; 

   if is_source(file) {
       if worth_counting(file) ++num_source_files;
       if license_conclude from SPDX for file != (NONE or NOASSERTION) then
          ++num_license_concluded;
       if license_possible from SPDX for file != (NONE or NOASSERTION) then
           ++num_license_possible

       }
    }
```

**Comment by pombredanne** [comment]
@kestewart  what did you mean by license_possible ?

**Comment by kestewart** [comment]
@krysnuvadga @pombredanne - I was using it as short hand for 4.11 License Information in File
 (ie. https://spdx.org/spdx-specification-21-web-version#h.111kx3o ).   Basically there has been something detected that could be a license reference by the scanner, etc. but it has not been concluded to be an actual valid license reference.

**Comment by pombredanne** [comment]
@kestewart FWIW my hunch is that the presence of concluded licenses will be a rare event in the case where SPDX docs are just fresh off a scan.

**Comment by kestewart** [comment]
@pombredanne, it will probably depend on the scanners and default behaviors,  which is why its important to summarize both individually at this stage.
